name: Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpcap-dev libncurses5-dev libssl-dev libcurl4-openssl-dev libjson-c-dev make gcc

    - name: Build project
      run: |
        make
        chmod +x anyintruder

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: anyintruder
        draft: false
        prerelease: false
        body_path: RELEASE_NOTES.md
